#!/usr/local/bin/bash

MAP_FILE='map.txt'
MAP_SIZE='map_size.tt'
REFRESH_RATE=.40

while [ "true" ]; do
	echo \#VARIABLE MAP_ROWS $(tput lines)\; > $MAP_SIZE
	echo \#VARIABLE MAP_COLS $(tput cols)\; >> $MAP_SIZE
	cat $MAP_FILE
	sleep $REFRESH_RATE
    clear
done
